#!/usr/bin/env python3
"""
Compare the oil-rate models in backtest_steady_rate.py on the SAME pickups,
scoring every eligible pickup rather than a sample.

A model can drop a pickup when it cannot form a rate (last-1 drops one), so a
pickup is compared only when every model in the comparison scored it. That
makes each row a like-for-like comparison.

The head-to-head (last 6 vs previous year) carries a paired bootstrap: for each
customer its shared pickups are resampled with replacement, both models' WAPE
recomputed on the same draw, and the 2.5th-97.5th percentile of the difference
reported. A difference whose interval spans zero is not distinguishable from
noise at this sample size.

The ±45-day calendar windows are left out: they read pickups after the one
being predicted, so they are a benchmark, not a candidate.

    python3 analysis/compare_models.py

Writes analysis/model_comparison.md. Analysis only.
"""

import random
from collections import defaultdict
from pathlib import Path

import backtest_steady_rate as bt

HERE = Path(__file__).resolve().parent
OUT = HERE / "model_comparison.md"

MODELS = ([{"kind": "window", "n": n} for n in range(1, bt.MAX_WINDOW + 1)]
          + [{"kind": "year", "days": bt.YEAR_DAYS}])
LAST_6 = {"kind": "window", "n": 6}
PREV_YEAR = {"kind": "year", "days": bt.YEAR_DAYS}

BOOTSTRAP_DRAWS = 2000
SEED = 42
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()


def label(model):
    return "prev year" if model["kind"] == "year" else f"last {model['n']}"


def score_all(pickups):
    """model label -> {(customer_id, pickup index): test} over every eligible pickup."""
    scored = {}
    for model in MODELS:
        tests = {}
        for cid in bt.SAMPLE:
            eligible, _ = bt.eligible_tests(cid, pickups[cid], model)
            # The pickup's index in the customer's history identifies it
            # uniquely, same-day pickups included.
            tests.update({(cid, t["prior_pickup_count"]): t for t in eligible})
        scored[label(model)] = tests
    return scored


def shared(scored, labels):
    keys = set.intersection(*(set(scored[l]) for l in labels))
    return sorted(keys)


def wape(tests):
    return sum(abs(t["_signed"]) for t in tests) / sum(t["actual_gallons"] for t in tests) * 100


def wape_diff_interval(pairs_by_customer, rng):
    """2.5/97.5 percentiles of WAPE(b) - WAPE(a), resampling within each customer."""
    diffs = []
    for _ in range(BOOTSTRAP_DRAWS):
        err_a = err_b = volume = 0
        for pairs in pairs_by_customer:
            for _ in range(len(pairs)):
                a, b = pairs[rng.randrange(len(pairs))]
                err_a += abs(a["_signed"])
                err_b += abs(b["_signed"])
                volume += a["actual_gallons"]
        diffs.append((err_b - err_a) / volume * 100)
    diffs.sort()
    return diffs[int(0.025 * BOOTSTRAP_DRAWS)], diffs[int(0.975 * BOOTSTRAP_DRAWS) - 1]


def verdict(lo, hi):
    if hi < 0:
        return "prev year better"
    if lo > 0:
        return "last 6 better"
    return "no clear difference"


def main():
    pickups = bt.load_pickups()
    scored = score_all(pickups)
    labels = [label(m) for m in MODELS]
    names = {cid: pickups[cid][-1]["name"] for cid in bt.SAMPLE}
    lines = []
    out = lines.append

    # ── 1. Every model on the pickups they all scored ──
    keys = shared(scored, labels)
    out("# Oil-rate model comparison\n")
    out("Generated by `analysis/compare_models.py`. Every eligible pickup from "
        f"{bt.TEST_FROM.isoformat()} on, no sampling.\n")
    out(f"## All models on the same {len(keys)} pickups\n")
    out("| Model | Median APE | WAPE | MAPE | MAE (gal) | Bias |")
    out("|---|---:|---:|---:|---:|---:|")
    for l in labels:
        m = bt.metrics([scored[l][k] for k in keys])
        out(f"| {l} | {m['median_ape']:.1f}% | {m['wape']:.1f}% | {m['mape']:.1f}% | "
            f"{m['mae']:.1f} | {m['bias_pct']:+.1f}% |")
    dropped = {l: len(scored[l]) for l in labels if len(scored[l]) != max(map(len, scored.values()))}
    if dropped:
        out("\nModels that could not score every pickup: "
            + ", ".join(f"{l} scored {n}" for l, n in dropped.items()) + ".")

    # ── 2. WAPE per customer, every model ──
    out(f"\n## WAPE by customer, every model\n")
    out("Same shared pickups. Lowest WAPE per customer in bold.\n")
    out("| Customer | n | " + " | ".join(labels) + " |")
    out("|---|---:|" + "---:|" * len(labels))
    by_cid = defaultdict(list)
    for k in keys:
        by_cid[k[0]].append(k)
    for cid in sorted(by_cid, key=lambda c: names[c]):
        row = {l: wape([scored[l][k] for k in by_cid[cid]]) for l in labels}
        best = min(row.values())
        cells = [f"**{v:.1f}%**" if v == best else f"{v:.1f}%" for v in row.values()]
        out(f"| {names[cid]} | {len(by_cid[cid])} | " + " | ".join(cells) + " |")

    # ── 3. Head-to-head: last 6 vs previous year ──
    a, b = label(LAST_6), label(PREV_YEAR)
    keys = shared(scored, [a, b])
    by_cid = defaultdict(list)
    for k in keys:
        by_cid[k[0]].append(k)
    rng = random.Random(SEED)

    out(f"\n## Head-to-head: {a} vs {b}\n")
    out(f"{len(keys)} shared pickups. **Difference** is WAPE({b}) − WAPE({a}): "
        f"negative means {b} is better. The 95% interval is a paired bootstrap "
        f"({BOOTSTRAP_DRAWS} draws, resampling within each customer).\n")
    out(f"| Customer | n | Mean actual | WAPE {a} | WAPE {b} | Difference | 95% interval | "
        f"Median APE {a} | Median APE {b} | Bias {a} | Bias {b} | Verdict |")
    out("|---|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---|")

    rows = []
    for cid in bt.SAMPLE:
        ta = [scored[a][k] for k in by_cid[cid]]
        tb = [scored[b][k] for k in by_cid[cid]]
        ma, mb = bt.metrics(ta), bt.metrics(tb)
        lo, hi = wape_diff_interval([list(zip(ta, tb))], rng)
        rows.append((names[cid], len(ta), ma, mb, lo, hi))
    for name, n, ma, mb, lo, hi in sorted(rows, key=lambda r: r[3]["wape"] - r[2]["wape"]):
        out(f"| {name} | {n} | {ma['mean_actual']:.1f} | {ma['wape']:.1f}% | {mb['wape']:.1f}% | "
            f"{mb['wape'] - ma['wape']:+.1f} | {lo:+.1f} to {hi:+.1f} | "
            f"{ma['median_ape']:.1f}% | {mb['median_ape']:.1f}% | "
            f"{ma['bias_pct']:+.1f}% | {mb['bias_pct']:+.1f}% | {verdict(lo, hi)} |")

    ta = [scored[a][k] for k in keys]
    tb = [scored[b][k] for k in keys]
    ma, mb = bt.metrics(ta), bt.metrics(tb)
    lo, hi = wape_diff_interval(
        [[(scored[a][k], scored[b][k]) for k in by_cid[cid]] for cid in bt.SAMPLE], rng)
    out(f"| **All customers** | {len(keys)} | {ma['mean_actual']:.1f} | {ma['wape']:.1f}% | "
        f"{mb['wape']:.1f}% | {mb['wape'] - ma['wape']:+.1f} | {lo:+.1f} to {hi:+.1f} | "
        f"{ma['median_ape']:.1f}% | {mb['median_ape']:.1f}% | "
        f"{ma['bias_pct']:+.1f}% | {mb['bias_pct']:+.1f}% | {verdict(lo, hi)} |")

    # ── 4. By calendar month ──
    out(f"\n## {a} vs {b} by month of the pickup\n")
    out("All customers pooled. A seasonally neutral rate should lean high in slow "
        "months and low in busy ones; this shows whether it does.\n")
    out(f"| Month | n | WAPE {a} | WAPE {b} | Bias {a} | Bias {b} | Mean gap (days) |")
    out("|---|---:|---:|---:|---:|---:|---:|")
    by_month = defaultdict(list)
    for k in keys:
        by_month[int(scored[a][k]["test_pickup_date"][5:7])].append(k)
    for month in sorted(by_month):
        ta = [scored[a][k] for k in by_month[month]]
        tb = [scored[b][k] for k in by_month[month]]
        ma, mb = bt.metrics(ta), bt.metrics(tb)
        gap = sum(t["days_since_previous"] for t in ta) / len(ta)
        out(f"| {MONTHS[month - 1]} | {len(ta)} | {ma['wape']:.1f}% | {mb['wape']:.1f}% | "
            f"{ma['bias_pct']:+.1f}% | {mb['bias_pct']:+.1f}% | {gap:.1f} |")

    out("\n## Caveats\n")
    out("- **The bootstrap treats pickups as independent.** Consecutive pickups share "
        "most of their training window, so their errors are correlated and the true "
        "intervals are somewhat wider than shown. A difference that only just clears "
        "zero should be read as a lean, not a result.")
    out("- **Hand-picked sample.** Eleven customers chosen because they look steady. "
        "A best case, not an estimate for the customer base.")

    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote analysis/{OUT.name}")


if __name__ == "__main__":
    main()
