#!/usr/bin/env python3
"""
Out-of-sample test of the routing rule read off backtest_seasonal_models.py:

    closes seasonally (quietest month < 10% of average)  -> no rule yet; reported apart
    seasonal repeatability >= 0.6                         -> seasonal blend
    everyone else                                         -> 50/50 last 6 + prev year

The rule came from the 20 customers in that backtest, so it is scored here only
on customers who were not among them: every customer with a pickup in each year
2022-2026 averaging at least HOLDOUT_MIN_GALLONS a year over 2023-25, minus
those 20. The cut sits below the seasonal pool's 1,000 because the remaining
customers above 1,000 include none with repeatability >= 0.6, which would leave
half the rule untested.

The rule and this script were fixed before any holdout result was seen. Nothing
is tuned. Model definitions are in backtest_seasonal_models.py.

    python3 analysis/test_routing_rule.py

Writes analysis/routing_rule_test.md and routing_rule_test_customers.csv.
Analysis only.
"""

import csv
import random
import statistics
from collections import defaultdict
from pathlib import Path

import backtest_seasonal_models as bsm
import backtest_steady_rate as bt
import seasonality_score as ss

HERE = Path(__file__).resolve().parent
OUT = HERE / "routing_rule_test.md"
PER_CUSTOMER = HERE / "routing_rule_test_customers.csv"

HOLDOUT_MIN_GALLONS = 500
ROUTE_MIN_REPEAT = 0.6

LAST6, FIFTY, BLEND, RATIO = bsm.MODELS
SINGLE = [LAST6, FIFTY, BLEND]
SHORT = bsm.SHORT

BOOTSTRAP_DRAWS = 2000
SEED = 42


def shaped_the_rule(pickups):
    """The 20 customers backtest_seasonal_models.py scored: the steady sample
    plus every pool customer classed seasonal."""
    pool = ss.high_producers(pickups)
    return set(bt.SAMPLE) | {c for c in pool if ss.classify(ss.score(pickups[c])) == "seasonal"}


def route(score):
    if score["trough_index"] < bsm.CLOSED_INDEX:
        return None
    return BLEND if score["repeatability"] >= ROUTE_MIN_REPEAT else FIFTY


def wape(tests):
    return bsm.wape(tests)


def interval(pairs_by_customer, rng):
    """Paired bootstrap of WAPE(first) − WAPE(second), resampling within customers."""
    diffs = []
    for _ in range(BOOTSTRAP_DRAWS):
        ea = eb = vol = 0
        for ps in pairs_by_customer:
            for _ in range(len(ps)):
                a, b = ps[rng.randrange(len(ps))]
                ea += abs(a["_signed"])
                eb += abs(b["_signed"])
                vol += a["actual_gallons"]
        diffs.append((ea - eb) / vol * 100)
    diffs.sort()
    return diffs[int(0.025 * BOOTSTRAP_DRAWS)], diffs[int(0.975 * BOOTSTRAP_DRAWS) - 1]


def main():
    pickups = bt.load_pickups(ids=None)
    used = shaped_the_rule(pickups)
    holdout = [c for c in ss.high_producers(pickups, HOLDOUT_MIN_GALLONS) if c not in used]

    customers, no_tests = {}, []
    for cid in holdout:
        ps = pickups[cid]
        s = ss.score(ps)
        rows, _ = bsm.score_customer(cid, ps, "holdout")
        if not rows:
            no_tests.append(ps[-1]["name"])
            continue
        tests = defaultdict(list)
        for t in rows:
            tests[t["model"]].append(t)
        customers[cid] = {"name": ps[-1]["name"], "town": ps[-1]["town"], "score": s,
                          "route": route(s), "tests": tests}

    routed = {c: v for c, v in customers.items() if v["route"]}
    closers = {c: v for c, v in customers.items() if not v["route"]}
    branches = {BLEND: {c: v for c, v in routed.items() if v["route"] == BLEND},
                FIFTY: {c: v for c, v in routed.items() if v["route"] == FIFTY}}

    def pooled(group, model):
        return [t for v in group.values() for t in v["tests"][model]]

    def routed_tests(group):
        return [t for v in group.values() for t in v["tests"][v["route"]]]

    rng = random.Random(SEED)
    lines = []
    out = lines.append

    out("# Routing rule — out-of-sample test\n")
    out("Generated by `analysis/test_routing_rule.py`. The rule, fixed before any result "
        "here was seen:\n")
    out(f"- **closes seasonally** (quietest month under {bsm.CLOSED_INDEX:.0%} of average) — "
        "no rule yet, reported apart")
    out(f"- **repeatability ≥ {ROUTE_MIN_REPEAT}** → seasonal blend")
    out("- **everyone else** → 50/50 last 6 + prev year\n")
    out(f"**Holdout:** {len(holdout)} customers with a pickup in every year "
        f"{ss.POOL_YEARS[0]}–{ss.POOL_YEARS[-1]} averaging at least {HOLDOUT_MIN_GALLONS} "
        f"gallons a year, excluding the {len(used)} used to find the rule. "
        f"{len(branches[BLEND])} routed to the blend, {len(branches[FIFTY])} to 50/50, "
        f"{len(closers)} close seasonally"
        + (f", {len(no_tests)} with no scorable pickup" if no_tests else "") + ".\n")

    # ── 1. The rule against one model for everyone ──
    rt = routed_tests(routed)
    out(f"## The rule vs one model for everyone — {len(routed)} customers, {len(rt)} pickups\n")
    out("**Difference** is the rule's WAPE minus the other's, in points; negative means "
        f"the rule is better. 95% interval: paired bootstrap, {BOOTSTRAP_DRAWS} draws, "
        "resampling within each customer.\n")
    out("| Approach | Median APE | WAPE | MAPE | Bias | Rule minus this | 95% interval |")
    out("|---|---:|---:|---:|---:|---:|---|")
    m = bt.metrics(rt)
    out(f"| **routing rule** | {m['median_ape']:.1f}% | {m['wape']:.1f}% | {m['mape']:.1f}% | "
        f"{m['bias_pct']:+.1f}% | — | — |")
    for model in SINGLE:
        o = bt.metrics(pooled(routed, model))
        lo, hi = interval([list(zip(v["tests"][v["route"]], v["tests"][model]))
                           for v in routed.values()], rng)
        out(f"| {model} for all | {o['median_ape']:.1f}% | {o['wape']:.1f}% | {o['mape']:.1f}% | "
            f"{o['bias_pct']:+.1f}% | {m['wape'] - o['wape']:+.1f} | {lo:+.1f} to {hi:+.1f} |")

    # ── 2. Each branch: did it pick the right model? ──
    out("\n## Each branch of the rule\n")
    out("Within each branch, the model the rule chose against the one it passed over.\n")
    out("| Branch | Customers | Pickups | last 6 | 50/50 | blend | Chosen minus passed-over "
        "| 95% interval | Customers where chosen was better |")
    out("|---|---:|---:|---:|---:|---:|---:|---|---|")
    for chosen, group in branches.items():
        if not group:
            out(f"| → {SHORT[chosen]} | 0 | — | — | — | — | — | — | — |")
            continue
        other = FIFTY if chosen == BLEND else BLEND
        w = {mo: wape(pooled(group, mo)) for mo in SINGLE}
        lo, hi = interval([list(zip(v["tests"][chosen], v["tests"][other]))
                           for v in group.values()], rng)
        hits = sum(1 for v in group.values() if wape(v["tests"][chosen]) <= wape(v["tests"][other]))
        out(f"| → {SHORT[chosen]} | {len(group)} | {len(pooled(group, LAST6))} | "
            f"{w[LAST6]:.1f}% | {w[FIFTY]:.1f}% | {w[BLEND]:.1f}% | "
            f"{w[chosen] - w[other]:+.1f} | {lo:+.1f} to {hi:+.1f} | {hits} of {len(group)} |")

    # ── 3. Period split ──
    out("\n## By period\n")
    out("| Period | Pickups | rule | last 6 | 50/50 | blend |")
    out("|---|---:|---:|---:|---:|---:|")
    for label, years in (("2023–24", (2023, 2024)), ("2025–26", (2025, 2026))):
        keep = lambda ts: [t for t in ts if int(t["test_pickup_date"][:4]) in years]
        r = keep(rt)
        out(f"| {label} | {len(r)} | {wape(r):.1f}% | "
            + " | ".join(f"{wape(keep(pooled(routed, mo))):.1f}%" for mo in SINGLE) + " |")

    # ── 4. Repeatable customers in detail ──
    out(f"\n## Customers routed to the blend\n")
    out("| Customer | Town | Gal/yr | Amplitude | Repeat | n | last 6 | 50/50 | blend |")
    out("|---|---|---:|---:|---:|---:|---:|---:|---:|")
    for cid, v in sorted(branches[BLEND].items(), key=lambda kv: -kv[1]["score"]["repeatability"]):
        s = v["score"]
        w = {mo: wape(v["tests"][mo]) for mo in SINGLE}
        best = min(w.values())
        cells = [f"**{x:.1f}%**" if x == best else f"{x:.1f}%" for x in w.values()]
        out(f"| {v['name']} | {v['town']} | {s['avg_gallons_per_year']:,.0f} | "
            f"{s['amplitude']:.2f} | {s['repeatability']:.2f} | {len(v['tests'][LAST6])} | "
            + " | ".join(cells) + " |")

    # ── 5. Closers ──
    out(f"\n## Customers that close seasonally — {len(closers)}\n")
    if closers:
        out("| Customer | Town | Trough | n | last 6 | 50/50 | blend | ratio |")
        out("|---|---|---:|---:|---:|---:|---:|---:|")
        for cid, v in sorted(closers.items(), key=lambda kv: kv[1]["name"]):
            w = [wape(v["tests"][mo]) for mo in bsm.MODELS]
            best = min(w)
            out(f"| {v['name']} | {v['town']} | {v['score']['trough_index']:.2f} | "
                f"{len(v['tests'][LAST6])} | "
                + " | ".join(f"**{x:.1f}%**" if x == best else f"{x:.1f}%" for x in w) + " |")
        out(f"\nPooled: " + ", ".join(f"{SHORT[mo]} {wape(pooled(closers, mo)):.1f}%"
                                       for mo in bsm.MODELS) + ".")

    out("\n## Caveats\n")
    out("- **Customer scores use the test years.** Each holdout customer's repeatability is "
        "computed from 2023–25, the years its pickups are scored on. The customers are out of "
        "sample; the classification is not. A production version would score each customer "
        "from history before the prediction.")
    out("- **Lower-volume customers are noisier.** Most of the holdout produces 500–1,000 "
        "gallons a year, so expect higher error across the board than the steady sample.")
    out("- **The bootstrap treats pickups as independent,** so true intervals are somewhat wider.")

    OUT.write_text("\n".join(lines) + "\n")

    fields = ["customer_id", "name", "town", "avg_gallons_per_year", "amplitude",
              "repeatability", "trough_index", "route", "pickups"] + [SHORT[m] for m in bsm.MODELS]
    with open(PER_CUSTOMER, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for cid, v in sorted(customers.items(), key=lambda kv: kv[1]["name"]):
            s = v["score"]
            w.writerow({"customer_id": cid, "name": v["name"], "town": v["town"],
                        "avg_gallons_per_year": round(s["avg_gallons_per_year"]),
                        "amplitude": round(s["amplitude"], 3),
                        "repeatability": round(s["repeatability"], 3),
                        "trough_index": round(s["trough_index"], 2),
                        "route": SHORT[v["route"]] if v["route"] else "closes seasonally",
                        "pickups": len(v["tests"][LAST6]),
                        **{SHORT[m]: round(wape(v["tests"][m]), 2) for m in bsm.MODELS}})

    print("\n".join(lines))
    print(f"\nWrote analysis/{OUT.name} and {PER_CUSTOMER.name}")


if __name__ == "__main__":
    main()
